<?php
/**
 * @copyright 2014 City of Bloomington, Indiana
 * @license http://www.gnu.org/licenses/agpl.txt GNU/AGPL, see LICENSE.txt
 * @author Cliff Ingham <inghamn@bloomington.in.gov>
 */
function mediamanager_admin_form()
{
	return system_settings_form([
		'mediamanager_url'=>[
			'#type'          => 'textfield',
			'#default_value' => variable_get('mediamanager_url'),
			'#title'         => 'Media Manager URL',
			'#description'   => 'The url of your installed Media Manager web application',
			'#required'      => true
		]
	]);
}

/**
 * Verifies the connection to Media Manager
 *
 * @implements hook_admin_validate()
 */
function mediamanager_admin_form_validate($form, &$form_state)
{
	// Make sure we can get back the media sizes
	$sizes = _mediamanager_sizes();
	if (!count($sizes)) {
		form_set_error('mediamanager_url', 'Cannot connect to Media Manager URL.  Make sure the URL is valid.');
	}
}

function mediamanager_menu()
{
	return [
		'admin/config/services/mediamanager' => [
			'title'           => 'Media manager settings',
			'description'     => 'Settings for the Media Manager module',
			'page callback'   => 'drupal_get_form',
			'page arguments'  => ['mediamanager_admin_form'],
			'access arguments'=> ['administer site configuration'],
			'type'            => MENU_NORMAL_ITEM
		]
	];
}

function mediamanager_field_info()
{
	return [
		'mediamanager' => [
			'label'            => t('Media Manager'),
			'description'      => t('Media from external manager'),
			'default_widget'   => 'mediamanager_mediaChooser',
			'default_formatter'=> 'mediamanager_mediaFormatter'
		]
	];
}

function mediamanager_field_widget_info()
{
	return [
		'mediamanager_mediaChooser' => [
			'label'         => t('External media'),
			'field types'   => ['mediamanager']
		]
	];
}

function mediamanager_field_widget_form(&$form, &$form_state, &$field, &$instance, &$langcode, &$items, &$delta, &$element)
{
	if ($instance['widget']['type'] == 'mediamanager_mediaChooser') {
		$url = variable_get('mediamanager_url');

		$element['media_id'] = [
            '#type'          => 'textfield',
            '#title'         => isset($instance['label']) ? $instance['label'] : 'Media ID',
            '#default_value' => isset($items[$delta])     ? $items[$delta]     : null,
            '#field_suffix'  => l('Media Manager', $url)
            //'#element_validate' => ['mediamanager_field_validate']
		];
	}
	return $element;
}

/**
 * Validate user entered media_id
 *
 * Users can enter ID in various ways:
 * int:       22
 * hex:       530778b93e0bf
 * media URL: http://localhost/media-manager/media/view?media_id=3
 * image url: http://localhost/media-manager/m/2014/2/21/350/530778b93e0bf.png
 *
 * @implements hook_field_validate()
 */
function mediamanager_field_validate($entity_type, $entity, $field, $instance, $lang, &$items, &$errors)
{
	foreach ($items as $delta=>$item) {
		if (!empty($item['media_id'])) {
			$id = _mediamanager_get_valid_id($item['media_id']);
			if (!$id) {
				$errors[$field['field_name']][$lang][$delta][] = [
					'error'   => 'unknownMedia',
					'message' => 'The media id you provided is not valid'
				];
			}
		}
	}
}

function mediamanager_field_presave($entity_type, $entity, $field, $instance, $lang, &$items)
{
	foreach ($items as $delta=>$item) {
		if (!empty($item['media_id'])) {
			$items[$delta]['media_id'] = _mediamanager_get_valid_id($item['media_id']);
		}
	}
}

function mediamanager_field_is_empty($item, $field)
{
	if ($field['type'] == 'mediamanager') {
		return empty($item['media_id']);
	}
}

function mediamanager_field_formatter_info()
{
	return [
		'mediamanager_mediaFormatter' => [
			'label'       => t('Default'),
			'field types' => ['mediamanager'],
			'settings'    => ['size'=>'']
		]
	];
}

function mediamanager_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state)
{
	$display = $instance['display'][$view_mode];
	$settings = $display['settings'];

	switch ($display['type']) {
		case 'mediamanager_mediaFormatter':
			$options = [];
			foreach (_mediamanager_sizes() as $name=>$size) {
				$options[$name] = $name;
			}

			$form['size'] = [
				'#title' => '',
				'#type' => 'select',
				'#empty_option' => t('None (original image)'),
				'#default_value' => $settings['size'],
				'#options'=> $options
			];
		break;
	}
	return $form;
}

function mediamanager_field_formatter_settings_summary($field, $instance, $view_mode)
{
	$settings = $instance['display'][$view_mode]['settings'];
	return empty($settings['size']) ? 'Original Image' : 'Media Size: '.$settings['size'];
}

function mediamanager_field_formatter_view($type, $entity, $field, $instance, $lang, $items, $display)
{
	$element = [];

	switch ($display['type']) {
		case 'mediamanager_mediaFormatter':
			$mediamanager_url = variable_get('mediamanager_url');

			foreach ($items as $delta=>$item) {
				$media = _mediamanager_media_info($item['media_id']);
				if ($media) {
					$element[$delta] = [
						'#theme' => 'mediamanager_media',
						'#media' => $media,
						'#size'  => $display['settings']['size']
					];
				}
			}
		break;
	}
	return $element;
}

function mediamanager_theme()
{
	return [
		'mediamanager_media'=>[
			'variables'=>['media'=>null, 'size'=>null]
		]
	];
}

function theme_mediamanager_media($var)
{
	$url = variable_get('mediamanager_url');
	$d = date('Y/n/j', strtotime($var['media']->uploaded));

	if ($var['size']) {
		$json = _mediamanager_sizes();
		$size = $json->$var['size'];

		$f = explode('.', $var['media']->internalFilename);
		$var['path'] = "$url/m/$d/$size/$f[0].png";
	}
	else {
		$var['path'] = "$url/m/$d/{$var['media']->internalFilename}";
	}

	return theme('image', $var);
}

function _mediamanager_sizes()
{
	$url = variable_get('mediamanager_url').'/derivatives?format=json';
	$response = drupal_http_request($url);
	return json_decode($response->data);
}

/**
 * @param int|hex $id
 * @return StdObject JSON response from media manager
 */
function _mediamanager_media_info($id)
{
	$url = variable_get('mediamanager_url')."/media/view?format=json&media_id=$id";

	$response = drupal_http_request($url);
	return json_decode($response->data);
}

/**
 * Validate user entered value and return media_id
 *
 * Returns null on validation error
 *
 * Users can enter ID in various ways:
 * int:       22
 * hex:       530778b93e0bf
 * media URL: http://localhost/media-manager/media/view?media_id=3
 * image url: http://localhost/media-manager/m/2014/2/21/350/530778b93e0bf.png
 *
 * @param string $id
 * @return int
 */
function _mediamanager_get_valid_id($id)
{
	$id = trim($id);

	if (   preg_match('|media_id=(\d+)|',         $id, $matches)
		|| preg_match('|([0-9a-f]{13})(.\w+)?$|', $id, $matches) ) {
		$id = $matches[1];
	}

	$media = _mediamanager_media_info($id);
	if ($media) {
		return $media->id;
	}
}
